Create 78.html
technologieplauscherl/technologieplauscherl.github.io pull request #232
Opened 2022-10-08 07:48 UTC by Yolgie

2022-10-08 07:49 UTC, Yolgie commented
not sure what the old map coordinates are or if we can just omit them

used the embed link for google maps, or should this be a different one?

also did not see the location image used in the current techplauscherl html page so not sure what the format should be :)

2022-10-08 07:50 UTC, Yolgie commented
@hupfis is this correct like this :)

2022-10-12 19:07 UTC, hupfis requested changes
Please add the event ids of the various platforms

2022-10-12 19:07 UTC, hupfis commented on _plauscherl/78.html
> +  meetup:
289070850

2022-10-12 19:07 UTC, hupfis commented on _plauscherl/78.html
> +  facebook:
441756534713264

2022-10-12 19:07 UTC, hupfis commented on _plauscherl/78.html
> +  linkedin:
6986039174076219393

2022-11-03 20:20 UTC, merged